### ISSUE TITLE
Cripplingly slow performance on large HTML files

### ISSUE THREAD

**Issue by fake-name** [rareyman/HTMLBeautify#49]
#### Issue description

Basically, if you try to use this plugin on a large HTML file (I'm dealing with a ~6.5 MByte file), it completely locks the editor up for long enough (multiple minutes) that I just killed the process.

#### Steps to reproduce the issue

1.  Open large HTML file.
2.  Run beautifier
3.  Try to interact with the editor.

#### What's the actual result?

The entire Sublime Text editor becomes completely unresponsive, and fails to do anything.

#### What's the expected result?

I'd expect the beautifier to actually use a HTML parser.

# [STOP PARSING HTML WITH REGULAR EXPRESSIONS!](https://stackoverflow.com/a/1732454/268006)

As a comparison, I shoved the HTML file in question into beautiful soup 4, and it took maybe 4 seconds to completely parse the file.

**Comment by fake-name** [comment]
Edit: I gave it about 5 minutes to run, and it finished.

And indented the file wrong.

Seriously, just use the actual correct tool for the purpose.

**Comment by rareyman** [comment]
@fake-name: Wow. Sooooo much _anger_. :| Thanks for the tip about `BeautifulSoup`. For whatever it is worth, this script started as a hack back in 1998 in the early days of web development. I originally created this as a personal script since I was unsatisfied with the editors and tools that were available at the time. I only distributed it here on GitHub in hopes it would help others out—but I **never** claimed it was the most efficient method of parsing HTML. It is just a simple method I thought I would share in the spirit of open source. You are absolutely correct—in today‘s world, regular expressions should be avoided since it is inefficient intros case. Perhaps some day I will adjust the script to upgrade the tool. Anyway, thanks for the feedback.

**Comment by fake-name** [comment]
I twas supposed to be somewhat tongue in cheed, but maybe I conveyed that wrong.

**Comment by rareyman** [comment]
No worries! :) Your comment came across as a little “angry”… but I decided to give you the benefit of the doubt. I'm guessing you were just hoping to improve the script and offering up sage advice—and for that I am grateful! Thanks, and have an awesome evening/day!

**Comment by fake-name** [comment]
I tend to be horrible at expressing myself on the internet, it's an ongoing problem I have, sorry about that.

Have you checked out the stack exchange link in the H1? It's in a pretty similar vein.

**Comment by dserodio** [comment]
@fake-name, how can I test your fork? Do you plan on submitting a PR? Thanks.

**Comment by fake-name** [comment]
@dserodio - I'm not sure, other then manually ploping my modified file into your Sublime Text extension folder over the existing one.

Also, it's already a PR: https://github.com/rareyman/HTMLBeautify/pull/50
