### ISSUE TITLE
HTML comments after tags causes indent to not work properly

### ISSUE THREAD

**Issue by FSXAC** [rareyman/HTMLBeautify#51]
Comments placed before or after the **opening tag** on the same line of the tag will cause the lines after to not be indented when they should be. (see first image)

Comments placed before or after the **closing tag** on the same line of the tag will cause the lines after to not be unindented when they should be. (see second image)

*img 1*
![htmlsublimebug2](https://user-images.githubusercontent.com/7558835/29435794-46145d7e-835d-11e7-8061-43e9362451e9.PNG)

*img 2*
![htmlsublimebug1](https://user-images.githubusercontent.com/7558835/29435793-4613d58e-835d-11e7-8705-48d9cb75e09f.PNG)

**Comment by rareyman** [comment]
Yup. This is a known bug. I tried to express that clearly in the README: https://github.com/rareyman/HTMLBeautify#notes ("Currently, this script chokes a bit with inline comments.")

This script parses through each line and makes indenting decisions based on the contents. Mixing comments and HTML code confuses the script which explains why this happens. :|

I'm hoping to address this issue in a future update! @fake-name has suggested using a new HTML parser instead of using REGEX to parse through the code. There is a pretty good chance this may solve this issue. Stay tuned. https://github.com/rareyman/HTMLBeautify/pull/50
